### ISSUE TITLE
What is a license of thie implementation?

### ISSUE THREAD

**Issue by seieric** [zcemycl/PyTorch-DeepFloorplan#5]
@zcemycl Hi, what is a license of codes in this repository? I'm wondering whether I can use this for my work.

**Comment by zcemycl** [comment]
I just added the MIT License.

**Comment by seieric** [comment]
Thank you very much for a quick reply.
Just in case, let me ask one more. Was this repository made from scratch? I want to make sure this repo doesn’t include any original GPL code.
